// <auto-generated />
using System;
using DIS.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DIS.ApiTwo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DIS.Backend.Models.Cycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CycleId"));

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CycleId");

                    b.HasIndex("PersonId");

                    b.ToTable("Cycles");

                    b.HasData(
                        new
                        {
                            CycleId = 1,
                            CycleNumber = 1,
                            EndDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 1,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.DailyLog", b =>
                {
                    b.Property<int>("DailyLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyLogId"));

                    b.Property<int>("CycleDay")
                        .HasColumnType("integer");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FlowLevelId")
                        .HasColumnType("integer");

                    b.HasKey("DailyLogId");

                    b.HasIndex("CycleId");

                    b.HasIndex("FlowLevelId");

                    b.ToTable("DailyLogs");

                    b.HasData(
                        new
                        {
                            DailyLogId = 1,
                            CycleDay = 1,
                            CycleId = 1,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowLevelId = 3
                        },
                        new
                        {
                            DailyLogId = 2,
                            CycleDay = 2,
                            CycleId = 1,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowLevelId = 2
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.DailyLogSymptom", b =>
                {
                    b.Property<int>("DailyLogId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalSymptomId")
                        .HasColumnType("integer");

                    b.HasKey("DailyLogId", "PhysicalSymptomId");

                    b.HasIndex("PhysicalSymptomId");

                    b.ToTable("DailyLogSymptoms");

                    b.HasData(
                        new
                        {
                            DailyLogId = 1,
                            PhysicalSymptomId = 2
                        },
                        new
                        {
                            DailyLogId = 1,
                            PhysicalSymptomId = 4
                        },
                        new
                        {
                            DailyLogId = 2,
                            PhysicalSymptomId = 1
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.FlowLevel", b =>
                {
                    b.Property<int>("FlowLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlowLevelId"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlowLevelId");

                    b.ToTable("FlowLevels");

                    b.HasData(
                        new
                        {
                            FlowLevelId = 1,
                            Amount = "None"
                        },
                        new
                        {
                            FlowLevelId = 2,
                            Amount = "Light"
                        },
                        new
                        {
                            FlowLevelId = 3,
                            Amount = "Medium"
                        },
                        new
                        {
                            FlowLevelId = 4,
                            Amount = "Heavy"
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Birthdate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "Female",
                            Name = "Test User"
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.PhysicalSymptom", b =>
                {
                    b.Property<int>("PhysicalSymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhysicalSymptomId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PhysicalSymptomId");

                    b.ToTable("PhysicalSymptoms");

                    b.HasData(
                        new
                        {
                            PhysicalSymptomId = 1,
                            Name = "Headache"
                        },
                        new
                        {
                            PhysicalSymptomId = 2,
                            Name = "Cramps"
                        },
                        new
                        {
                            PhysicalSymptomId = 3,
                            Name = "Sore breasts"
                        },
                        new
                        {
                            PhysicalSymptomId = 4,
                            Name = "Tiredness"
                        },
                        new
                        {
                            PhysicalSymptomId = 5,
                            Name = "Back pain"
                        });
                });

            modelBuilder.Entity("DIS.Backend.Models.Cycle", b =>
                {
                    b.HasOne("DIS.Backend.Models.Person", "Person")
                        .WithMany("Cycles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DIS.Backend.Models.DailyLog", b =>
                {
                    b.HasOne("DIS.Backend.Models.Cycle", "Cycle")
                        .WithMany("DailyLogs")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIS.Backend.Models.FlowLevel", "FlowLevel")
                        .WithMany("DailyLogs")
                        .HasForeignKey("FlowLevelId");

                    b.Navigation("Cycle");

                    b.Navigation("FlowLevel");
                });

            modelBuilder.Entity("DIS.Backend.Models.DailyLogSymptom", b =>
                {
                    b.HasOne("DIS.Backend.Models.DailyLog", "DailyLog")
                        .WithMany("DailyLogSymptoms")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIS.Backend.Models.PhysicalSymptom", "PhysicalSymptom")
                        .WithMany("DailyLogSymptoms")
                        .HasForeignKey("PhysicalSymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");

                    b.Navigation("PhysicalSymptom");
                });

            modelBuilder.Entity("DIS.Backend.Models.Cycle", b =>
                {
                    b.Navigation("DailyLogs");
                });

            modelBuilder.Entity("DIS.Backend.Models.DailyLog", b =>
                {
                    b.Navigation("DailyLogSymptoms");
                });

            modelBuilder.Entity("DIS.Backend.Models.FlowLevel", b =>
                {
                    b.Navigation("DailyLogs");
                });

            modelBuilder.Entity("DIS.Backend.Models.Person", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("DIS.Backend.Models.PhysicalSymptom", b =>
                {
                    b.Navigation("DailyLogSymptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
